routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('pages/{theme}', 'Frontend\PageController@index')->name('pages.show');


// Admin
Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){
	//admin
	Route::get('/','Backend\DashboardController@index')->name('admin.dashboard');
	
	//Themes 
	 Route::resource('themes','Backend\ThemeController');
	
	//Onepages 
	 Route::resource('onepages','Backend\OnepageController');
	

});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Onepage.php
<?php

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Onepage extends Eloquent
{
    //
	  protected $collection = 'onepages';

	  public function sections()
    {
        return $this->hasMany('App\Models\Section','id_onepage','_id');
    } 

    public function menuLists()
    {
        return $this->hasOne('App\Models\MenuList','id_onepage','_id');
    }

    public function slides()
    {
        return $this->hasMany('App\Models\Slide','id_onepage','_id');
    }

 		public function notes()
    {
        return $this->hasMany('App\Models\Note','id_onepage','_id');
    }

		public function oneposts()
    {
        return $this->hasMany('App\Models\Onepost','id_onepage','_id');
    }

    public function accordions()
    {
        return $this->hasMany('App\Models\Accordion','id_onepage','_id');
    }

    public function products()
    {
        return $this->hasMany('App\Models\Product','id_onepage','_id');
    }

    public function pricings()
    {
        return $this->hasMany('App\Models\Pricing','id_onepage','_id');
    }

    public function works()
    {
        return $this->hasMany('App\Models\Work','id_onepage','_id');
    }

    public function swipings()
    {
        return $this->hasMany('App\Models\Swiping','id_onepage','_id');
    }

    public function services()
    {
        return $this->hasMany('App\Models\Service','id_onepage','_id');
    }

    public function contacts()
    {
        return $this->hasMany('App\Models\Contact','id_onepage','_id');
    }


}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    //
	public function index(){
		
       return view('backend.dashboard.index');
		
	}

}

app/Http/Controllers/Backend/OnepageController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Onepage;

use App\Models\Section;
use App\Models\MenuList;
use App\Models\Slide;
use App\Models\Note;
use App\Models\Onepost;
use App\Models\Accordion;
use App\Models\Product;
use App\Models\Pricing;
use App\Models\Work;
use App\Models\Swiping;
use App\Models\Service;
use App\Models\Contact;


class OnepageController extends Controller
{
  protected $vars = array();
   

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
       $onepages = Onepage::all();
        //dd($onepages);

        return view('backend.onepages.index')->with([
                                    'onepages'=> $onepages,
                                    ]);;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('backend.onepages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $input = $request->all();

        $theme = $request->nameTheme;
        $site_name = $request->nameOnepage;

//-----------------------------------------
        $config_site = config('themes.'.$theme.'.site');

       //dd($config_site);

        $onepage = new Onepage;
            
             $onepage->name = $site_name;
             $onepage->theme = $theme;

             foreach ($config_site as $name => $value) {
                    $onepage->$name = $value;
             }
        $onepage->save();


//----------------    !!!!!!!!!!!!!!!    ------------------------
        $config_section = config('themes.'.$theme.'.sections');
        $position = 1;
        
             foreach ($config_section as $key => $item) {
                $section = new Section;
                 $section->position = $position++; 
                   foreach ($item as $name => $value) {
                         $section->$name = $value;                      
                    }
                $onepage->sections()->save($section);
             }
        
//----------------    !!!!!!!!!!!!!!!    ------------------------
        $config_list = config('themes.'.$theme.'.menuLists');
       
        foreach ($config_list as $key => $item) {
            $menuList = new MenuList;
                 foreach ($item as $name => $value) {
                    $menuList->$name = $value;
                 }
            $onepage->menuLists()->save($menuList);
        }
//------------------------------------------
        $config_slide = config('themes.'.$theme.'.slides');

        foreach ($config_slide as $key => $item) {
            $slide = new Slide;
                  foreach ($item as $name => $value) {
                       $slide->$name = $value;
                    }
            $onepage->slides()->save($slide);
         }   
//------------------------------------------
        $config_note = config('themes.'.$theme.'.notes');

        foreach ($config_note as $key => $item) {
             $note = new Note;
                 foreach ($item as $name => $value) {
                    $note->$name = $value;
                 }
            $onepage->notes()->save($note);
        }
//------------------------------------------
        $config_onepost = config('themes.'.$theme.'.oneposts');

        foreach ($config_onepost as $key => $item) {
            $onepost = new Onepost;
                 foreach ($item as $name => $value) {
                    $onepost->$name = $value;
                }
            $onepage->oneposts()->save($onepost);
         }
//------------------------------------------
        $config_accordion = config('themes.'.$theme.'.accordions');

        foreach ($config_accordion as $key => $item) {
            $accordion = new Accordion;
                foreach ($item as $name => $value) {
                       $accordion->$name = $value;
                }
            $onepage->accordions()->save($accordion);
         }
//------------------------------------------
        $config_product = config('themes.'.$theme.'.products');

        foreach ($config_product as $key => $item) {
             $product = new Product;
                foreach ($item as $name => $value) {
                    $product->$name = $value;
                }
            $onepage->products()->save($product);
        }
//------------------------------------------
        $config_pricing = config('themes.'.$theme.'.pricings');

        foreach ($config_pricing as $key => $item) {
            $pricing = new Pricing;
                foreach ($item as $name => $value) {
                    $pricing->$name = $value;
                }
            $onepage->pricings()->save($pricing);
         }
//------------------------------------------
        $config_work = config('themes.'.$theme.'.works');

        foreach ($config_work as $key => $item) {
            $work = new Work;
                foreach ($item as $name => $value) {
                    $work->$name = $value;
                }
            $onepage->works()->save($work);
         }
//------------------------------------------
        $config_swiping = config('themes.'.$theme.'.swipings');

        foreach ($config_swiping as $key => $item) {
            $swiping = new Swiping;
                foreach ($item as $name => $value) {
                    $swiping->$name = $value;
                }
            $onepage->swipings()->save($swiping);
         }
//------------------------------------------
        $config_service = config('themes.'.$theme.'.services');

        foreach ($config_service as $key => $item) {
            $service = new Service;
                foreach ($item as $name => $value) {
                    $service->$name = $value;
                }
            $onepage->services()->save($service);
         }
//------------------------------------------
        $config_contact = config('themes.'.$theme.'.contacts');

        foreach ($config_contact as $key => $item) {
            $contact = new Contact;
                foreach ($item as $name => $value) {
                    $contact->$name = $value;
                }
            $onepage->contacts()->save($contact);
         }
//-----------------------------------------------------------

        


echo "string";
   //  return redirect()->route('profile', [$user]);

        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $onepage = Onepage::find($id);

        $this->vars = array_add($this->vars,'onepage',$onepage);  

        $sections = $onepage->sections->sortBy('position');
        if (!empty($sections)) {
             $this->vars = array_add($this->vars,'sections',$sections);             
        }
       
        $menuLists = $onepage->menuLists;
        if (!empty($menuLists)) {
             $this->vars = array_add($this->vars,'menuLists',$menuLists);             
        }
       

        $slides = $onepage->slides;
        if (!empty($slides)) {
             $this->vars = array_add($this->vars,'slides',$slides);             
        }

        $notes = $onepage->notes;
         if (!empty($notes)) {
             $this->vars = array_add($this->vars,'notes',$notes);             
        }

        $oneposts = $onepage->oneposts;
         if (!empty($oneposts)) {
             $this->vars = array_add($this->vars,'oneposts',$oneposts);             
        }

        $accordions = $onepage->accordions;
        if (!empty($accordions)) {
             $this->vars = array_add($this->vars,'accordions',$accordions);             
        }

        $products = $onepage->products;
         if (!empty($products)) {
             $this->vars = array_add($this->vars,'products',$products);             
        }

        $pricings = $onepage->pricings;
        if (!empty($pricings)) {
             $this->vars = array_add($this->vars,'pricings',$pricings);             
        }

        $works = $onepage->works;
         if (!empty($works)) {
             $this->vars = array_add($this->vars,'works',$works);             
        }

        $swipings = $onepage->swipings;
         if (!empty($swipings)) {
             $this->vars = array_add($this->vars,'swipings',$swipings);             
        }

        $services = $onepage->services;
         if (!empty($services)) {
             $this->vars = array_add($this->vars,'services',$services);             
        }
            
         $contacts = $onepage->contacts;
         if (!empty($contacts)) {
             $this->vars = array_add($this->vars,'contacts',$contacts);             
        }
            

       // dd($sections);

       // echo ($onepage->name);
        return view('themes.'.$onepage->theme.'.index')->with($this->vars );


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        return view('backend.onepages.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/ThemeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Theme;

class ThemeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
         $sections = config('themes.onepage.sections');



        return view('backend.themes.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('backend.themes.create');


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
         echo "string";
       //dd($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/onepages/create.blade.php
@extends('backend.layouts.backend')

@section('content')    

<div class="container-fluid">
     
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{{ url('admin/')}}">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{{ url('admin/onepages')}}">One Pages</a>
    </li>
      <li class="breadcrumb-item active">Create One Page</li>
  </ol>
   <!-- END Breadcrumbs-->



  <!-- Example Create One Page Card-->
  <div class="card mb-3">
    <div class="card-header">
      <i class="fa fa-table"></i> Create One Page
    </div>
    <!-- /.card-header-->

    <div class="card-body">
    
    
  
   
          
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active " id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact</a>
  </li>
</ul>
<div class="tab-content " id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

  <div class="card mt-3">
     <!--  <div class="card-header">Register an Account</div> -->
      <div class="card-body">
        
<form action="{{ route('onepages.store') }}" method="POST">
   {{ csrf_field() }}

  <div class="form-group">
    <div class="form-row">
      <div class="col-md-12">

        <label for="nameTheme"> Name Theme</label>
        {{-- <input class="form-control" id="nameTheme" name="nameTheme" type="text" aria-describedby="nameHelp" placeholder="Enter Name theme">
 --}}

    <select class="form-control" id="nameTheme" name="nameTheme">
      <option>onepage</option>
     {{--  <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option> --}}
    </select>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="form-row">
      <div class="col-md-12">
        <label for="nameOnepage"> Name OnePage</label>
        <input class="form-control" id="nameOnepage" name="nameOnepage"  type="text" aria-describedby="nameHelp" placeholder="Enter Name OnePage">
      </div>
    </div>
  </div>

        <div class="form-group">
            
            <input type="submit" class="btn btn-primary btn-block" value="Отправить">
          </div>
          
        </form>
        
      </div>
    </div>

     
  </div>
  <div class="tab-pane fade border border-primary border-top-0" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
  <div class="tab-pane fade border border-primary border-top-0" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
</div>
 
<!-- ---------------- -->

    





  </div>
    <!-- /.card-body-->

    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
    <!-- /.card-footer -->
  </div>
   <!-- /.card -->
      
</div>
<!-- /.container-fluid-->
    

   
@endsection

resources/views/backend/onepages/edit.blade.php
@extends('backend.layouts.backend')

@section('content')    

<div class="container-fluid">
     
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{{ url('admin/')}}">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{{ url('admin/onepages')}}">OnePage</a>
    </li>
      <li class="breadcrumb-item active">Edit OnePage</li>
  </ol>
   <!-- END Breadcrumbs-->



          
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active " id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contact</a>
  </li>
</ul>
<div class="tab-content " id="myTabContent">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

  <div class="card mt-3">
     <!--  <div class="card-header">Register an Account</div> -->
      <div class="card-body">
        
<form action="{{ route('onepages.store') }}" method="POST">
   {{ csrf_field() }}

  <div class="form-group">
    <div class="form-row">
      <div class="col-md-12">

        <label for="nameTheme"> Name Theme</label>
        {{-- <input class="form-control" id="nameTheme" name="nameTheme" type="text" aria-describedby="nameHelp" placeholder="Enter Name theme">
 --}}

    <select class="form-control" id="nameTheme" name="nameTheme">
      <option>onepage</option>
     {{--  <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option> --}}
    </select>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="form-row">
      <div class="col-md-12">
        <label for="nameOnepage"> Name OnePage</label>
        <input class="form-control" id="nameOnepage" name="nameOnepage"  type="text" aria-describedby="nameHelp" placeholder="Enter Name OnePage">
      </div>
    </div>
  </div>

        <div class="form-group">
            
            <input type="submit" class="btn btn-primary btn-block" value="Отправить">
          </div>
          
        </form>
        
      </div>
    </div>

     
  </div>
  <div class="tab-pane fade border border-primary border-top-0" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
  <div class="tab-pane fade border border-primary border-top-0" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
</div>
 
<!-- ---------------- -->

    


      
</div>
<!-- /.container-fluid-->
    

   
@endsection

resources/views/backend/onepages/index.blade.php
@extends('backend.layouts.backend')

@section('content')    

   <div class="container-fluid">

      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">OnePages</li>
      </ol>



      


      <!-- Example DataTables Card-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> Data Table OnePages

          <div class="btn-group float-right" role="group" aria-label="Basic example">
               <a id="new_theme"class="btn btn-outline-success" href="{{ route('onepages.create') }}" role="button"><i class="fa fa-lg fa-plus"  title="Add Theme"></i></a>
            
          </div>

        </div>


        <div class="card-body">
 @if(isset($onepages) && is_object($onepages))    

          <div class="table-responsive">
            <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Title</th>
                  <th>Descriptipn</th>
                  <th>Theme</th>
                  
                  <th>Actions</th>
                </tr>
              </thead>

              <tfoot>
                <tr>
                  <th>Name</th>
                  <th>Title</th>
                  <th>Descriptipn</th>
                  <th>Theme</th>
                  
                  <th>Actions</th>
                </tr>
              </tfoot>
              <tbody>


 @foreach($onepages as $onepage)
                <tr>
                  <td>{{ $onepage->name }}</td>
                  <td>{{ $onepage->title }}</td>
                  <td>{{ $onepage->descriptipn }}</td>
                  <td>{{ $onepage->theme }}</td>
                  
                  
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              
              <a id="new_onepage"class="btn btn-outline-info" href="{{ route('onepages.show',$onepage->_id) }}" role="button"><i class="fa fa-lg fa-eye"  title="View"></i></a>

               <a id="edit_onepage"class="btn btn-outline-warning" href="{{ route('onepages.edit',$onepage->_id) }}" role="button"><i class="fa fa-lg fa-pencil"  title="Edit"></i></a>


              <button type="button" title="Delete" class="btn btn-outline-danger"><i class="fa fa-lg fa-trash"></i></button>
            </div>
          </td>
                </tr>
               
 @endforeach
                
              </tbody>
            </table>
          </div>
@endif

        </div>

        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>
    </div>
    <!-- /.container-fluid-->
    

   
@endsection